# -*- coding: utf-8 -*-
"""webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxZBb_ewISpEn13RD0LwCbHEX-lvUkbE
"""

!pip install google-colab-selenium

import os

os.chdir("/content/drive/MyDrive")
print(os.getcwd())

#scraping data from amazon.in

import requests
from bs4 import BeautifulSoup
import time
import random
import pandas as pd
import google_colab_selenium as gs
from selenium.webdriver.common.by import By

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,TimeoutException



url="https://www.amazon.in/s?k=laptop&crid=1TG9GAZO1RQWR&sprefix=lap%2Caps%2C794&ref=nb_sb_noss_2"
driver=gs.Chrome()








headers = {
        'User-Agent':"'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'"
    }
url="https://www.amazon.in/s?k=laptop&crid=1TG9GAZO1RQWR&sprefix=lap%2Caps%2C794&ref=nb_sb_noss_2"

time_delay=random.uniform(5,8)
print(f"Getting The Website in {time_delay:.2f} Seconds>")
time.sleep(time_delay)
driver.get(url)



if "404" in driver.current_url or "Page Not Found" in driver.title:
  print("Failed to retrieve the page")


else:
  data={"Name":[],"Current_price":[],"Original_price":[],"Ratings":[],"Availability":[]}
  count=0
  page_count=1
  while True:

      time.sleep(random.uniform(3,6))
      print("Connection Sucessful.")
      soup=BeautifulSoup(driver.page_source,"html.parser")
      links=soup.find_all("a",attrs={"class":"a-link-normal s-line-clamp-2 s-line-clamp-3-for-col-12 s-link-style a-text-normal"})

      links=[link.get("href") for link in links if link.get("href")]
      links=["https://www.amazon.in"+link for link in links]
      print(f"{page_count} page scraping...")
      page_count+=1


      for link in links:


          driver.get(link)
          time.sleep(random.uniform(1,3))
          try:
            name=driver.find_element(By.CSS_SELECTOR,"span.a-size-large.product-title-word-break").text.strip()
          except:
            name="N/A"
          try:
            current_price=driver.find_element(By.CSS_SELECTOR,"span.a-price-whole").text.strip()

          except:
            current_price="N/A"
          try:
            orginal_price=driver.find_element(By.CSS_SELECTOR,"span.a-price.a-text-price span.a-offscreen").find_element(By.CSS_SELECTOR,"span.a-offscreen").text.strip()
          except:
            orginal_price="N/A"
          try:
            ratings=driver.find_element(By.CSS_SELECTOR,"span.a-icon-alt").text.strip()
          except:
            ratings="N/A"
          try:
            availability=driver.find_element(By.ID,"availability").text.strip()
          except:
            availability="N/A"

          if name=="N/A" or current_price=="N/A":
            driver.get(url)
            continue
          if orginal_price=="N/A":
            orginal_price=current_price

          data["Name"].append(name)
          data["Current_price"].append(current_price)
          data["Original_price"].append(orginal_price)
          data["Ratings"].append(ratings)
          data["Availability"].append(availability)
          count+=1
          print(f"Product {count} Scraped")

          driver.get(url)
          time.sleep(random.uniform(1,3))
      try:
        next_button=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.CSS_SELECTOR,"a.s-pagination-next")))
        next_button.click()

      except (NoSuchElementException,TimeoutException):
        print("No more pages to scrape.")
        break

df=pd.DataFrame.from_dict(data)
df.to_csv("Amazon_laptops.csv",index=False)
print(df)
driver.quit()